### ISSUE TITLE
PDO MySQL does not support SSL.

### ISSUE THREAD

**Issue by TheRyanHowell** [facebook/hhvm#3493]
It appears that PDO is missing SSL support in the MySQL driver.

```
Fatal error: Couldn't find constant PDO::MYSQL_ATTR_SSL_KEY
```

After using the reflection class, the following constants are missing

```
PDO::MYSQL_ATTR_SSL_CA
PDO::MYSQL_ATTR_SSL_CAPATH
PDO::MYSQL_ATTR_SSL_CERT
PDO::MYSQL_ATTR_SSL_CIPHER
PDO::MYSQL_ATTR_SSL_KEY
```

**Comment by iansltx** [comment]
Still missing :(

**Comment by gfleury** [comment]
Im working on it, soon as i assume it is stable i will create a pull request

https://github.com/gfleury/hhvm/tree/ADD_PDO_SSL_SUPPORT

**Comment by gfleury** [comment]
Done, PR #5101

**Comment by maurocolella** [comment]
Not working in 3.8.

**Comment by paulbiss** [comment]
@maurocolella The PR was never merged. There were unresolved test failures.

**Comment by maurocolella** [comment]
Thank you for the reply Paul, but this is penalizing. If I want to access a
database server over a network, even a small network (if I have, say, two
public-facing instances with a host), I can restrict accesses by IP of
course, but my passwords will always be briefly visible. For every user and
on every request.

**Comment by jprlauzier** [comment]
It seems that it is still not updated with 3.9.1 - I agree with @maurocolella, it is an important feature. I unfortunately have to uninstall HHVM because I need to use certificates with my databases. Any ETA? Thanks.

**Comment by kel** [comment]
Running into this same issue. Need to connect to DB with SSL.

**Comment by sheybey** [comment]
You can work around this issue by using the number the constant evaluates to as a literal. The value of `PDO::MYSQL_ATTR_SSL_CA` from php 5.5, which is `1009`, works in HHVM 3.10.
```php
$db = new PDO("mysql:..", "username", "password", array(
    //This constant is undefined in hhvm
    //PDO::MYSQL_ATTR_SSL_CA => '/etc/ssl/certs/ca.pem'
    1009 => '/etc/ssl/certs/ca.pem'
));
```

**Comment by Orvid** [comment]
Does that connect properly via SSL? I know it won't error, but it is probably just ignoring the option.

**Comment by sheybey** [comment]
Orvid is right, it is just falling back to non-ssl silently. My mistake assuming it would error out when passed invalid options...

**Comment by croemmich** [comment]
Any update on this?

**Comment by TheDeadCode** [comment]
+1

**Comment by zhil** [comment]
+1

**Comment by jesseschalken** [comment]
This should have been fixed by https://github.com/facebook/hhvm/commit/96da765cedb434ee8e4d20a9837320dafdf6f142
