### ISSUE TITLE
Segfault when resuming from xdebug breakpoint in PHPStorm (and maybe other places?)

### ISSUE THREAD

**Issue by jaredkipe** [facebook/hhvm#4351]
Here is the contents of the stacktrace:

```
Host: app1
ProcessID: 18253
ThreadID: 7f2172fff700
ThreadPID: 18257
Name: unknown program
Type: Segmentation fault
Runtime: hhvm
Version: tags/HHVM-3.4.0-0-g817b3a07fc4e509ce15635dbc87778e5b3496663
DebuggerCount: 0


#0  folly::IOBuf::countChainElements() const at /usr/local/bin/hhvm:0
#1  apache::thrift::async::TAsyncSocket::writeChain(apache::thrift::async::TAsyncTransport::WriteCallback*, std::unique_ptr<folly::IOBuf, std::default_delete<folly::IOBuf> >&&, apache::thrift::async::WriteFlags) at /usr/local/bin/hhvm:0
#2  HPHP::FastCGISession::writeStream(unsigned short, HPHP::FastCGISession::RecordType, std::unique_ptr<folly::IOBuf, std::default_delete<folly::IOBuf> >) at /usr/local/bin/hhvm:0
#3  HPHP::FastCGITransaction::onStdOut(std::unique_ptr<folly::IOBuf, std::default_delete<folly::IOBuf> >) at /usr/local/bin/hhvm:0
#4  std::_Function_handler<void (), HPHP::FastCGITransport::sendImpl(void const*, int, int, bool)::{lambda()#1}>::_M_invoke(std::_Any_data const&) at fastcgi-transport.cpp:0
#5  folly::EventBase::runFunctionPtr(std::function<void ()>*) at /usr/local/bin/hhvm:0
#6  folly::EventBase::FunctionRunner::messageAvailable(std::pair<void (*)(void*), void*>&&) at /usr/local/bin/hhvm:0
#7  folly::NotificationQueue<std::pair<void (*)(void*), void*> >::Consumer::handlerReady(unsigned short) at /usr/local/bin/hhvm:0
#8  event_base_loop at /usr/lib/x86_64-linux-gnu/libevent-2.0.so.5:0
#9  folly::EventBase::loopBody(int) at /usr/local/bin/hhvm:0
#10 folly::EventBase::loopForever() at /usr/local/bin/hhvm:0
#11 proxygen::WorkerThread::runLoop() at /usr/local/bin/hhvm:0
#12 std::thread::_Impl<std::_Bind_simple<proxygen::WorkerThread::start()::{lambda()#1} ()> >::_M_run() at WorkerThread.cpp:0
#13 std::this_thread::__sleep_for(std::chrono::duration<long, std::ratio<1l, 1l> >, std::chrono::duration<long, std::ratio<1l, 1000000000l> >) at /usr/lib/x86_64-linux-gnu/libstdc++.so.6:0
#14 start_thread at /lib/x86_64-linux-gnu/libpthread.so.0:0
#15 clone at /lib/x86_64-linux-gnu/libc.so.6:0
```

This MAY have been caused by an exception in a registered callback for __SystemLib\SessionForwardingHandler->close()

**Comment by jwatzman** [comment]
- This happens with any breakpoint, in any project? (Trying to get a repro case.)
- Have you tried with the recently released 3.5?

**Comment by roman-shuhov** [comment]
happens in any project with any type of breakpoint
also happens in 3.5.0

**Comment by jwatzman** [comment]
Sounds like we have some consistent reports. The xdebug/phpstorm thing is worth looking into when we get some time -- the issue seems to happen with more than just that, but it sounds like a consistent repro.

**Comment by sobit** [comment]
happens to me also on remote debugging using phpstorm

**Comment by SvetlanaZem** [comment]
Hello, I'm working on debugger integration in PhpStorm and I'll be happy to provide you any information that will help to fix the issue. So if you need any assistance feel free to contact me.

**Comment by RoyHP** [comment]
I am also having this problem, with the same steps using phpstorm.

**Comment by jwatzman** [comment]
@paulbiss do you know if anyone is actively working on xdebug? Might be useful to take up @SvetlanaZem's offer if someone is, though I suspect we don't have anyone with the spare time right now?

**Comment by paulbiss** [comment]
@alexmalyshev is working on hphpd, and had been looking at Xdebug as a potential replacement. I think he handed off the Xdebug work to the IDE folks, but he may know who was looking at it most recently anyway.

**Comment by RoyHP** [comment]
If they are useful, I have attached HHVM's xdebug logs to the PhpStorm issue WI-26478 (https://youtrack.jetbrains.com/issue/WI-26478). I think @SvetlanaZem believes this is an issue with HHVM. Let me know if there's anything you want me to test.

**Comment by SvetlanaZem** [comment]
There are three responses for a single "breakpoint_set" command in xdebug.log files provided by @RoyHP Anyway it looks like another problem, please let me know if I should create separate issue.

**Comment by RoyHP** [comment]
@jwatzman Someone is reporting this issue is not only limited to PHPStorm, but also happening with MacGDBp. They are commenting on the issue I created with PHPStorm in my last comment.

**Comment by MaXal** [comment]
Issue is still there for HHVM 3.7.0.

**Comment by bheyser** [comment]
I can also confirm the issue:
- hhvm 3.7.0 via nginx
- phpstorm 8.0.3
- ilias 5.0.1 - php project with db based session storage

happens after resuming from a breakpoint

**Comment by robertodormepoco** [comment]
same here with HHVM 3.7.0/Nginx with PhpStorm EAP or 8.0.*

the xdebug communication works quite well in Eclipse Luna 4.4, mainly because xdebug and the later talk with a different sequence of communication steps

**Comment by robertodormepoco** [comment]
please see [my colleague's post](https://github.com/facebook/hhvm/issues/4488) about hhvm xdebug read buffer handling

**Comment by jwatzman** [comment]
Can someone who was having this problem try it again with the latest nightly build of HHVM? #4488 has been fixed and I wonder if this is too.

**Comment by RoyHP** [comment]
@jwatzman Someone on #4488 is having a new problem. I haven't tried it yet myself, and won't get the chance for a while.

**Comment by jwatzman** [comment]
Leaving this open until confirmed fixed, but won't be personally working on it right now.

**Comment by th3fallen** [comment]
Not sure if related but my xdebug will not stop at a breakpoint it always stops at first line of first file. also results in random segfaults in HHVM 3.9.1

**Comment by euphio** [comment]
The problem still exists for us when remote debugging to a Vagrant box:
 - Ubuntu 14.04
 - PhpStorm 9.0.2
 - HHVM 3.9.2

Resuming from a breakpoint intermittently causes a segfault.

**Comment by paulbiss** [comment]
Is anyone still seeing this? The recent work on xdebug for nuclide debugging support fixed a lot of hard to find bugs.

**Comment by mofarrell** [comment]
Closing.  Needs more info.  (https://github.com/facebook/hhvm/wiki/Human-Timeouts)
