### ISSUE TITLE
hhvm rewriting rules broken

### ISSUE THREAD

**Issue by cyrilmarois** [facebook/hhvm#6738]
Hi people,

I have an issue related to rewriting url with hhvm
I have build a php (5.6.16 (fpm)) webapp using laravel (5.0.33), running under debian jessie (8.2) with apache (2.4.10)
Everything works fine, and the pretty urls works like the fact that I do not have to include index.php in my URI.
However, since I have installed hhvm (3.11.0), the pretty url does not works anymore and I have no other choice than added the index.php in my URI otherwise it throws me  404

I already had a look on those #6695, and #3472 but not sure they are related

**Comment by javacty** [comment]
if you use nginx+hhvm(fastcgi), just config rewrite rule in nginx config file use try_file, pretty well.

if you use hhvm(libevent),  show me the rewrite rule you need, i will translate it into hhvm.hdf

**Comment by cyrilmarois** [comment]
Hi @javacty, 

First of all thanks for your feedback.
As I mentionned I am running apache httpd server, and according to https://github.com/facebook/hhvm/wiki/Runtime-options, the .hdf files will be deprecated so I'm using the default .ini config file which looks like this :

```
; php options
pid = /var/run/hhvm/pid
; hhvm specific 
hhvm.server.port = 9000
hhvm.server.type = fastcgi
hhvm.server.default_document = index.php
hhvm.server.source_root = /var/www/laravel
hhvm.server.fix_path_info = true
hhvm.server.error_document404 = unknown.php
hhvm.log.level = Debug
hhvm.log.always_log_unhandled_exceptions = true
hhvm.log.use_log_file = true
hhvm.log.file = /var/log/hhvm/error.log
hhvm.repo.central.path = /var/run/hhvm/hhvm.hhbc
```

if you want to have a look on my apache config
**Remember that it does work on php fpm**

```
<VirtualHost *:80>
    ServerName  laravel.dev
    DocumentRoot /var/www
    ProxyPassMatch ^/(.+\.(hh|php)(/.*)?)$ fcgi://127.0.0.1:9000/var/www/laravel/$1
    <Directory /var/www/laravel/public>
        <IfModule mod_rewrite.c>
            <IfModule mod_negotiation.c>
                Options -MultiViews
            </IfModule>

	    Options -Indexes +FollowSymLinks
            RewriteEngine On

            # Redirect Trailing Slashes...
            RewriteCond %{REQUEST_FILENAME} !-d
            RewriteRule ^(.*)/$ /$1 [L,R=301]

            # Secure Front Themes...
            RewriteRule ^themes/.*\.(blade.php|php)$ - [F,L,NC]

            # Handle Front Controller...
            RewriteCond %{REQUEST_FILENAME} !-d
            RewriteCond %{REQUEST_FILENAME} !-f
	    RewriteRule ^ index.php [L]
        </IfModule>             

        DirectoryIndex index.php 

        Require all granted
    </Directory>
</VirtualHost>
```
But when I ran 
```
sudo hhvm -m daemon -c server.ini -p 80
```

I have hhvm lauching my php files but the rewriting URL does not work

**Comment by fredemmott** [comment]
Likely related to https://github.com/facebook/hhvm/issues/6648 and fixed in nightlies (and 3.11.1 / 3.12.0 when they're out), and possibly the hhvm.server.fix_path_info ini setting needs setting to true.

**Comment by fredemmott** [comment]
@javacty: as an aside, the libevent server's been gone for quite a long time - the built-in HTTP server is now proxygen-based.

**Comment by cyrilmarois** [comment]
@fredemmott thanks, I will have a look and test it when I will have time

**Comment by cyrilmarois** [comment]
@fredemmott I have the feeling I miss something, or I still have an issue.
Just grab and install with nightly repo the 3.12.0 and I have also set hhvm.server.fix_path_info = false
but I have 404 without index.php include in my URI

do I have to make new rewrite rules ?

**Comment by fredemmott** [comment]
From your rewrite rules, it looks like you want apache to turn anything that doesn't match a file into a request for index.php?

Is Apache raising the 404, or is HHVM? One way to check is to see if there's an X-Powered-By: HHVM header in the response

**Comment by cyrilmarois** [comment]
HHVM is running the script 
I suppose I'm missing something...

**Comment by cyrilmarois** [comment]
anyone ?

**Comment by jefferson-kaneta-oktagon** [comment]
I'm also having an issue with redirect using lighttpd and yii2 framework,
when I use php-fpm everything works, when i switch to hhvm the rewrite rules I'm using in lighttpd stops working.

**Comment by fredemmott** [comment]
To debug: It'd be handy if you could use tcpdump/wireshark to find out exactly what the webserver is asking HHVM for

To workaround: try setting `hhvm.server.default_document=index.php` `hhvm.server.error_document404=index.php`

Also, make sure that `hhvm.server.source_root` is set appropriately

**Comment by fredemmott** [comment]
Appropriately: if your code is in /var/www and apache is asking HHVM for '/var/www/index.php' for example, hhvm's source root should be '/'. If apache is just asking for 'index.php', hhvm's source root should be /var/www

**Comment by aorenste** [comment]
We've been unable to reproduce this bug, and are unable to investigate further. We are closing the issue for now, if you identify a test case we can use to reproduce your bug feel free to re-open.

This issue has been waiting for more info for more than 2 weeks. I'm closing it for now, but feel free to re-open it if you can provide more info. https://github.com/facebook/hhvm/wiki/Human-Timeouts
