### ISSUE TITLE
Memory leak when using += operator.

### ISSUE THREAD

**Issue by Norbyte** [facebook/hhvm#7071]
HHVM leaks memory when concatenating arrays using the += operator.

HipHop VM 3.12.2-dev (rel)
Compiler: remotes/origin/HHVM-3.12-0-g3b4d6db0f24236fddcd8c9313f9f8bf6f2c72f09
Repo schema: 5107bad6d6910a4bc292ad2910a6b5a39dc94f6d

Affected code:
```
for ($i = 0; $i < 100; $i++)
{   
    $a = [];
    $a += [str_repeat('x', 1000000)];
    echo memory_get_usage(true) . PHP_EOL;
}
```

Output:
```
2152872
3201496
4250104
5298744
6347352
7395960
[...]
```

If I replace `$a += [str_repeat('x', 1000000)];` by `$a = $a + [str_repeat('x', 1000000)];` or `array_merge`, memory usage doesn't grow anymore:
```
2152872
2152872
2152872
2152872
2152872
[...]
```

**Comment by jwatzman** [comment]
cc @paulbiss this might be worth trying to confirm and look into; `+=` is fairly common at FB. (Though if we had a serious leak there I'd be surprised if we hadn't found it by now.)

**Comment by Norbyte** [comment]
This does not leak memory permanently, it only causes an unexpected memory usage increase for the duration of the request by not releasing the objects in the `$a` array after it goes out of scope (mabe a refcount issue?).
However its still be a problem for long-running tasks that are using the `+=` operator. (That's how we discovered it)

**Comment by g33kyaditya** [comment]
@jwatzman If += causes the memory leak, would that mean, changing every instance of it's occurrence ?

**Comment by mpu** [comment]
I could not reproduce this on the stable version at FB, this might have been fixed.

**Comment by Orvid** [comment]
Yep, there was an issue like this that got fixed. Closing.

**Comment by jwatzman** [comment]
@Orvid care to link to the fix diff if you know where it is?

**Comment by Orvid** [comment]
I remember it coming through my emails, but I don't remember enough detail to find which diff it was :(

**Comment by dpaneda** [comment]
I'm still reproducing this issue with 3.12.8 and 3.15.3, and this is causing OOM errors on our productions servers. Any info about the changeset which have this fixed?
