### ISSUE TITLE
[bug] T_OPEN_TAG_WITH_ECHO not detected correctly

### ISSUE THREAD

**Issue by keradus** [facebook/hhvm#7161]
`T_OPEN_TAG_WITH_ECHO` is not detected correctly by tokenizer
Originally reported here: https://github.com/facebook/hhvm/issues/4809
But the bugfix didn't handle all cases :(
### HHVM Version

3.9.1, don't know if lower as well

Labels: php5 incompatibility
### Standalone code, or other way to reproduce the problem

``` php
<?php

$a = token_get_all("<?=' ';\n");
$b = token_get_all("<?\n?><?=' ';\n");

// both `<?=` should be T_OPEN_TAG_WITH_ECHO
var_dump(token_name($a[0][0]) === token_name($b[3][0]));
```
### Expected result

`bool(true)`
### Actual result

`bool(false)`

**Comment by SiebelsTim** [comment]
I think this is fixed in newer versions.

**Comment by keradus** [comment]
As you see, on `3.12.0` the bug is still there

**Comment by SiebelsTim** [comment]
This reminded me of #4809, but that's different apparently.

Looks like HHVM drops the second php-tags: https://3v4l.org/eAVIL

**Comment by keradus** [comment]
so long, yet no fixes...

**Comment by SpacePossum** [comment]
still broken (3.12.12 - 3.17.2), please @SiebelsTim can someone look at this, I hope it is `probably easy` as  labelled :)

**Comment by farizluqman** [comment]
Any updates?

**Comment by keradus** [comment]
ping ping ping

**Comment by keradus** [comment]
ping ping ping ping ping ping

**Comment by lexidor** [comment]
I am going over old issues on this repository, to see which ones apply to the current versions of hhvm.

`\token_get_all()` was [removed](https://github.com/facebook/hhvm/commit/898535bb43c5e504d0826104c1b654b0cf199228) in hhvm [4.0.0](https://hhvm.com/blog/2019/02/11/hhvm-4.0.0.html).
