### ISSUE TITLE
Compiling gives lots of "lambda capture initializers only available with -std=c++1y or -std=gnu++1y" warnings

### ISSUE THREAD

**Issue by derickr** [facebook/hhvm#7604]
### HHVM Version
3.12.12, 3.14.5

### Standalone code, or other way to reproduce the problem
Compiling this on Debian Unstable, with GCC 4.9 (forced, as 5.x didn't use to work at all), as well as with GCC 5.3.1

### Actual result
```
In file included from /home/derick/dev/facebook-hhvm/third-party/folly/folly/ThreadLocal.h:53:0,
                 from /home/derick/dev/facebook-hhvm/third-party/folly/folly/experimental/TLRefCount.h:18,
                 from /home/derick/dev/facebook-hhvm/third-party/folly/folly/experimental/ReadMostlySharedPtr.h:21,
                 from /home/derick/dev/facebook-hhvm/third-party/folly/folly/Singleton.h:112,
                 from /home/derick/dev/facebook-hhvm/hphp/util/compatibility.h:24,
                 from /home/derick/dev/facebook-hhvm/hphp/util/stack-trace.h:26,
                 from /home/derick/dev/facebook-hhvm/hphp/util/exception.h:24,
                 from /home/derick/dev/facebook-hhvm/hphp/util/exception.cpp:17:
/home/derick/dev/facebook-hhvm/third-party/folly/folly/detail/ThreadLocalDetail.h: In member function ‘void folly::threadlocal_detail::ElementWrapper::set(Ptr, const Deleter&)’:
/home/derick/dev/facebook-hhvm/third-party/folly/folly/detail/ThreadLocalDetail.h:110:53: warning: lambda capture initializers only available with -std=c++14 or -std=gnu++14
       deleter2 = new std::function<DeleterFunType>([d = d](
```

**Comment by mofarrell** [comment]
This should have been fixed [here](https://github.com/facebook/folly/commit/e6aa2684a75a8c3077a763fca674a79bb61b47ad) prior to the 3.15 cut.  I do not know if they were back ported to 3.12.  There is very little chance it is on the 3.14 branch as that was not an LTS release.  Is there a reason you are looking to build 3.12.12 and 3.14.5?  3.14 is not an LTS release, and 3.12 is going out of support February 13th 2017

**Comment by derickr** [comment]
I sadly don't have the luxury to just drop support for these HHVM versions (3.12 at least), because of our users (https://github.com/mongodb/mongo-hhvm-driver): https://docs.mongodb.com/ecosystem/drivers/driver-compatibility-reference/#reference-compatibility-language-php

I'll check whether 3.15.4 has the same issue tomorrow.

**Comment by mofarrell** [comment]
In any case every HHVM user should be transitioning away from 3.12 right now.  That being said it should still compile.  Was that error produced while building the 3.12 branch pulled off of github?  https://github.com/facebook/hhvm/tree/HHVM-3.12
It is worth noting you should grab the a new copy of the third party directory after checking out that branch.  It will have different revisions of all the third party modules.  Consider running `git clean -dfx && rm -rf third-party && git submodule update --init --recursive && cmake . && make -j8` after checking out that branch.

**Comment by derickr** [comment]
My rebuild script does exactly that, except for -j24 instead of -j8 ;-)

I didn't grab it from the tip of the branch, trying that now. But it was just a warning in 3.12 and 3.14 and not an error, so I'm happy for this report to just be closed. I was just making sure it wasn't something dangerous as I've been running into weird compiler errors lately.

**Comment by derickr** [comment]
The tip of ``HHVM-3.12`` still shows the warnings, and doesn't compile because of the "isnan" issue (https://github.com/facebook/hhvm/issues/6924). With a patch (http://derickrethans.nl/files/dump/hhvm-3.12.12.patch), it compiled.

The tip of ``HHVM-3.15`` does not show the warnings, and ```3.15.4`` doesn't build right now: https://github.com/facebook/hhvm/issues/7603#issuecomment-273732498).

**Comment by mofarrell** [comment]
Closing this.  The 3.15 issue you opened is still around.  If this is still an issue let me know.
